// User
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_LOADED = "USER_LOADED";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const ADDED_TO_WISHLIST = "ADDED_TO_WISHLIST";

// Categories
export const CATEGORY_CREATED = "CATEGORY_CREATED";
export const CATEGORY_FETCHED = "CATEGORY_FETCHED";
export const CATEGORY_UPDATED = "CATEGORY_UPDATED";
export const CATEGORY_DELETED = "CATEGORY_DELETED";
export const CATEGORY_LISTED = "CATEGORY_LISTED";

// Sub categories
export const SUB_CREATED = "SUB_CREATED";
export const SUB_FETCHED = "SUB_FETCHED";
export const SUB_UPDATED = "SUB_UPDATED";
export const SUB_DELETED = "SUB_DELETED";
export const SUB_LISTED = "SUB_LISTED";

// Products
export const PRODUCT_CREATED = "PRODUCT_CREATED";
export const PRODUCT_FETCHED = "PRODUCT_FETCHED";
export const PRODUCT_UPDATED = "PRODUCT_UPDATED";
export const PRODUCT_DELETED = "PRODUCT_DELETED";

export const PRODUCTS_LISTED = "PRODUCTS_LISTED";
export const SET_LIST_PRODUCTS_LOADING = "SET_LIST_PRODUCTS_LOADING";

export const CLEAR_CURRENT_PRODUCT = "CLEAR_CURRENT_PRODUCT";
export const SET_CURRENT_PRODUCT_LOADING = "SET_CURRENT_PRODUCT_LOADING";

export const LIST_BEST_SELLINGS = "LIST_BEST_SELLINGS";
export const CLEAR_BEST_SELLINGS = "CLEAR_BEST_SELLINGS";

export const LIST_NEW_ARRIVALS = "LIST_NEW_ARRIVALS";
export const CLEAR_NEW_ARRIVALS = "CLEAR_NEW_ARRIVALS";

export const PRODUCT_RATING_UPDATED = "PRODUCT_RATING_UPDATED";

export const SIMILAR_PRODUCTS_LISTED = "SIMILAR_PRODUCTS_LISTED";
export const SIMILAR_PRODUCTS_CLEARED = "SIMILAR_PRODUCTS_CLEARED";

export const PRODUCTS_BY_CATEOGRY_LISTED = "PRODUCTS_BY_CATEOGRY_LISTED";
export const PRODUCTS_BY_CATEGORY_CLEARED = "PRODUCTS_BY_CATEGORY_CLEARED";

export const PRODUCTS_BY_SUBS_LISTED = "PRODUCTS_BY_SUBS_LISTED";
export const PRODUCTS_BY_SUBS_CLEARED = "PRODUCTS_BY_SUBS_CLEARED";

export const FILTERED_PRODUCTS_LISTED = "FILTERED_PRODUCTS_LISTED";
export const FILTERED_PRODUCTS_CLEARED = "FILTERED_PRODUCTS_CLEARED";

export const SEARCH_TEXT_CHANGED = "SEARCH_TEXT_CHANGED";

// Cart
export const ADDED_TO_CART = "ADDED_TO_CART";
export const QTY_CHANGED = "QTY_CHANGED";
export const COLOR_CHANGED = "COLOR_CHANGED";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const GET_CART = "GET_CART";
export const CLEAR_CART_PRICE = "CLEAR_CART_PRICE";
export const CLEAR_CART = "CLEAR_CART";
export const APPLY_COUPON = "APPLY_COUPON";

// Drawer
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";

// Coupons
export const COUPON_CREATED = "COUPON_CREATED";
export const COUPON_LISTED = "COUPON_LISTED";
export const COUPON_DELETED = "COUPON_DELETED";

// Stripe
export const INTENT_CREATED = "INTENT_CREATED";
export const PAYMENT_COMPLETE = "PAYMENT_COMPLETE";

// Orders
export const ORDER_CREATED = "ORDER_CREATED";
export const USER_ORDERS_LISTED = "USER_ORDERS_LISTED";
export const ADMIN_ORDERS_LISTED = "ADMIN_ORDERS_LISTED";
export const ORDER_UPDATED = "ORDER_UPDATED";
