// User
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_LOADED = "USER_LOADED";

// Categories
export const CATEGORY_CREATED = "CATEGORY_CREATED";
export const CATEGORY_FETCHED = "CATEGORY_FETCHED";
export const CATEGORY_UPDATED = "CATEGORY_UPDATED";
export const CATEGORY_DELETED = "CATEGORY_DELETED";
export const CATEGORY_LISTED = "CATEGORY_LISTED";

// Sub categories
export const SUB_CREATED = "SUB_CREATED";
export const SUB_FETCHED = "SUB_FETCHED";
export const SUB_UPDATED = "SUB_UPDATED";
export const SUB_DELETED = "SUB_DELETED";
export const SUB_LISTED = "SUB_LISTED";

// Products
export const PRODUCT_CREATED = "PRODUCT_CREATED";
export const PRODUCT_FETCHED = "PRODUCT_FETCHED";
export const PRODUCT_UPDATED = "PRODUCT_UPDATED";
export const PRODUCT_DELETED = "PRODUCT_DELETED";

export const PRODUCTS_LISTED = "PRODUCTS_LISTED";
export const SET_LIST_PRODUCTS_LOADING = "SET_LIST_PRODUCTS_LOADING";

export const CLEAR_CURRENT_PRODUCT = "CLEAR_CURRENT_PRODUCT";
export const SET_CURRENT_PRODUCT_LOADING = "SET_CURRENT_PRODUCT_LOADING";

export const LIST_BEST_SELLINGS = "LIST_BEST_SELLINGS";
export const CLEAR_BEST_SELLINGS = "CLEAR_BEST_SELLINGS";

export const LIST_NEW_ARRIVALS = "LIST_NEW_ARRIVALS";
export const CLEAR_NEW_ARRIVALS = "CLEAR_NEW_ARRIVALS";

export const PRODUCT_RATING_UPDATED = "PRODUCT_RATING_UPDATED";

export const SIMILAR_PRODUCTS_LISTED = "SIMILAR_PRODUCTS_LISTED";
export const SIMILAR_PRODUCTS_CLEARED = "SIMILAR_PRODUCTS_CLEARED";
